### ISSUE TITLE
Document CircleCI workaround for expanding `~`

### ISSUE THREAD

**Issue by fermayo** [undefinedlabs/scope-docs#132]
In Circle CI, the following step has to be added before tests run so we can detect the proper source root directory:

```yaml
- run:
    name: Fix CIRCLE_WORKING_DIRECTORY
    command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
```

Source: https://discuss.circleci.com/t/circle-working-directory-doesnt-expand/17007/5
